### ISSUE TITLE
"Multiple modules with name" detection

### ISSUE THREAD

**Issue by danielbsig** [angular/batarang#210]
I'm getting the message above quite a few times, or more specifically:

Multiple modules with name "ui.bootstrap" are being created and they will overwrite each other.

... and similar messages for all of the submodules declared in ui.bootstrap. Now, obviously I'm including these modules more than once, but I can't find where the second include is. Would it be possible to somehow show where each module is defined?

**Comment by erwinmombay** [comment]
mind creating a reduction in a gist/plunk/fiddle?

**Comment by SomeKittens** [comment]
Closing, will reopen if we get a reproduction.

**Comment by rekaburmeister** [comment]
I just had this problem, I included both the -tpls and non-tpls js in my bundle config. 
It would have been useful to know however where the duplication occurred instead of simply saying "multiple modules with name [name]" something like "module [name] is loaded in [js1] and [js2]... [jsN]"

It was a silly mistake to make but with so many items of the "puzzle" relying on strings rather than names it would be nice to have more aids for debugging the issues.
