### ISSUE TITLE
Google extension unusable

### ISSUE THREAD

**Issue by RyanNerd** [angular/batarang#283]
Look at the extension reviews in the Google extension page:

The videos and what I get is not the same, actually batarang reminds me of a broken AngularJS page. 

---

Will HitchcockModified Nov 5, 2015

After months of having to use AngularJS Batarang (Stable) I was hoping that the recent updates would have made the latest versions usable. This is still totally worthless.

Probably the most important feature with this is the Performance tab. Unfortunately it's unusable and totally illegible with its weird spacing issues. Is it just broken and rendering wrong? I have no idea.

Hints are worthless too. "Consider changing HeaderCtrl to HeaderController". Really? Is that helpful? That's the only "hint" you can give me? Come on.

Stick to AngularJS Batarang (Stable) until this stuff gets worked out.

**Comment by SomeKittens** [comment]
The "weird spacing issue" was fixed in 0.10.4

The video update is issue #269

"worthless hints" are just reminders to follow what the Angular team considers best practices in naming.  You're welcome to ignore them if your team has different standards.

To be frank, reviews & issues like this are the reason none of us prioritize Batarang.  It has great potential but the community hates it so none of us put much time into it.

**Comment by RyanNerd** [comment]
I use ng-inspector because it's not broken. It works out of the box. Batarang USED TO WORK and has better features. But right now it's broken. I suppose some idiot decided the master branch should be the dev branch making breaking changes and Batarang went to hell after that. It worked about a year ago. Then I 'upgraded' and...
