### ISSUE TITLE
Can not enable this extension in chrome

### ISSUE THREAD

**Issue by chafel** [angular/batarang#294]
I can not enable this extension in chrome`Version 49.0.2623.112 (64-bit)` and `Version 52.0.2715.0 canary (64-bit)`.
And the console output error is:

> angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
> TypeError: Cannot set property 'aHrefSanitizationWhitelist' of null

**Comment by carlosromel** [comment]
@chafel, are you still using Chrome at this version (52.0.2715.0) ?
Maybe this issue can be closed, due the time lapse.

**Comment by leonardospina** [comment]
No please, same issue here:
Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
AngularJS Inspector 0.4.5
Javascript exception is thrown as soon as the Batarang "Enable" checkbox is checked.

This is the exception I'm currently getting:

Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.6.4/$injector/strictdi?p0=function(%24provide)
(...calls stack follows...)

**Comment by gkalpak** [comment]
I can't reproduce this error. Also @leonardospina's error seems different than @chafel.
Since @chafel's issue is with old version and we haven't heard from him, I am going to close this.
@leonardospina, if you are still seeing an error, please open a new issue with more details (e.g. a page that I can use to reproduce the error).
